### ISSUE TITLE
Runs out of memory

### ISSUE THREAD

**Issue by teymour-aldridge** [michal-h21/make4ht-action#5]
I have a document (https://github.com/teymour-aldridge/calculusoftheabsurd) which I can compile (with both `pdflatex` and `make4ht`) on my local machine (2021 MacTex installation – `make4ht version v0.3g` and `pdfTeX 3.141592653-2.6-1.40.22`), and it works fine (producing <https://notes.reasoning.page/html/main.html>). However, when I compile this using this Github action, although `pdflatex` works fine, `make4ht` runs out of memory (https://github.com/teymour-aldridge/calculusoftheabsurd/runs/6066343450?check_suite_focus=true).

I'm not sure if this is a bug in `make4ht` or this specific Docker image. Any help would be greatly appreciated.

**Comment by michal-h21** [comment]
Could you try to add the `-a debug` option to `make4ht` in `build.sh`? It could hopefully show more relevant information about what happens. But it seems like an infinite loop is executed somewhere. 

I can see one issue from your `pdflatex` run. Lot of messages like:
```

===== 'mode=convert with system call': Invoking ' pdflatex -shell-escape -halt-
on-error -interaction=batchmode -jobname "main-figure15" "\def\tikzexternalreal
job{main}\input{main}"; gs -dSAFER -r600 -sDEVICE=pngalpha -o "main-figure15.pn
g" "main-figure15.pdf" ' ========
[42]) (./chapters/differential_calc.tex [43 <./main-figure15.pdf>] [44]This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
sh: 1: gs: not found
```

So it seems that you expect GhostScript, but it not included in the Docker image. TeX Live contains it's own version of Ghostscript, called `rungs`. So in theory, it should be possible to change the following code from your `preamble.tex` from:

      gs -dSAFER -r600 -sDEVICE=pngalpha -o "\image.png" "\image.pdf"

to

      rungs -dSAFER -r600 -sDEVICE=pngalpha -o "\image.png" "\image.pdf"

I am not sure if it will fix the fatal error, hopefully yes.

**Comment by teymour-aldridge** [comment]
Thanks – that fixed the infinite loop. Thank you!
